name: 'RunTests'
description: 'Execute Playwright tests'
inputs:
  proj:  # id of input
    description: 'Project'
    required: false
    default: '--chromium'

runs:
  using: "node16"
  main:
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30